### ISSUE TITLE
I tried to putting the public key on google cloud shell, but it failed.

### ISSUE THREAD

**Issue by pqnhan** [FrancescoDiSalesGithub/Google-cloud-shell-hacking#1]
The reponse I get is "HTTP/1.1 500 Internal Server Error"
I followed the instructions but got here without success.
I don't know what to do next. 🙃

![image](https://user-images.githubusercontent.com/24197589/219323424-22db8571-93f4-4f62-b196-161f92210332.png)
![image](https://user-images.githubusercontent.com/24197589/219323048-34265769-2151-4471-946e-4344c939edb1.png)

**Comment by pqnhan** [comment]
Looks like these API doesn't work then.

![image](https://user-images.githubusercontent.com/24197589/219327089-b761bdcc-fd08-40f0-8afc-e7a50403bbba.png)

**Comment by pqnhan** [comment]
[It's looks like Google Cloud Shell VMs will automatically reset if bandwidth usage limit is exceeded](https://www.reddit.com/r/googlecloud/comments/112338q/does_google_cloud_shell_vms_will_automatically/)

I tried many times and confirm that.

**Comment by FrancescoDiSalesGithub** [comment]
Sorry for the absence.  Gonna check as soon as possible!

Thank you for opening the issue. :)

**Comment by FrancescoDiSalesGithub** [comment]
in the header authorization is missing Bearer as I see in the pic. It should be

Authorization: Bearer jkshfdfgusiugfisdf
