### ISSUE TITLE
code 500

### ISSUE THREAD

**Issue by kwekewk** [FrancescoDiSalesGithub/Google-cloud-shell-hacking#2]
error post pubkey from [this part](https://github.com/FrancescoDiSalesGithub/Google-cloud-shell-hacking#putting-the-public-key-on-google-cloud-shell
)
`{
  "error": {
    "status": "INTERNAL", 
    "message": "Internal error encountered.", 
    "code": 500
  }
}`

**Comment by FrancescoDiSalesGithub** [comment]
More details on the request?

**Comment by FrancescoDiSalesGithub** [comment]
Fixed the issue.

In the body add the following:

```

{
   "key":"ssh-rsa content-of-your-public-key"
}


```

**Comment by kwekewk** [comment]
ah my bad, i need to remove my username from pubkey, i think u should add reminder to readme.

btw can we do the same method starting shell as ephmeral mode??

**Comment by FrancescoDiSalesGithub** [comment]
I may think I have fixed that in the guide. Can you check for me?

Do you want Ephiimeral mode? Open another issue please. 

Thanks for your help. :)

**Comment by FrancescoDiSalesGithub** [comment]
No ephimeral mode start is available as for official documentation

**Comment by kwekewk** [comment]
> No ephimeral mode start is available as for official documentation

yeah, unfortunately the flags only applicable at web browser

**Comment by FrancescoDiSalesGithub** [comment]
Closing the issue since it was fixed. Thanks for the help

**Comment by FrancescoDiSalesGithub** [comment]
Issue fixed
